## Python Pizza Course 2019
# Numpy


## Introduction
Python was intented as a generic programming language, so there's no inbuilt supports for multidimensional arrays. However, as already introduced by Part #2, the library `numpy` has been built for doing just that.

Many of the operations in later modules will involve numpy arrays. Rasters, NetCDFs and other formats are often read in as such arrays. Therefore, we'll introduce the most common `numpy` operations here.

## Arrays
Numpy arrays are easier to use and faster to calculate on than the equivalent in Python. You can start with a list of numbers in Python and create an array from it.

In [43]:
import numpy as np # less typing
p_array = [1,2,3]
n_array = np.array([1,2,3])
print(n_array)

[1 2 3]


1

The same goes for multidimensional arrays, which would be a list of lists in Python.

In [8]:
p_array = [[1,2,3], [4,5,6]]
n_array = np.array(p_array, dtype=np.float64)
print(n_array)

[[1. 2. 3.]
 [4. 5. 6.]]


If you want to know about the `numpy` array, you can use the following functions to check its type, shape, size and dimensions.

In [9]:
print(n_array.dtype)
print(np.shape(n_array))  # rows, columns
print(np.size(n_array))
print(np.ndim(n_array))

float64
(2, 3)
6
2


You can also resize the array, either to flatten it to a vector (1 dimensional) or to actually resize it back from a vector to a matrix (2 dimensional).

In [10]:
vector = n_array.flatten()
print(vector)
print(vector.shape)  # can also be found as attribute

[1. 2. 3. 4. 5. 6.]
(6,)


In [19]:
matrix = np.reshape(vector, (2,3))  # determine shape in rows, columns
print(matrix)
print(np.shape(matrix))
matrix

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


(0,)

We can also create arrays via other methods. We can use a range of numbers, or an array with the same number everywhere.

In [20]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
np.empty((5,21)) # filled with random memory values

array([[ 1.28822975e-231,  1.28822975e-231,  2.21528004e-314,
         2.21530211e-314,  2.21530213e-314,  8.75332703e-251,
         0.00000000e+000,  3.95252517e-323,  3.66792210e-270,
         2.04199002e-212,  2.16916452e-314,  2.16724161e-314,
         3.46643323e+282,  2.16916462e-314,  2.16724161e-314,
         1.90939388e+193,  2.16916465e-314,  2.16724114e-314,
        -5.89441892e-215,  2.16916468e-314,  2.16724161e-314],
       [-7.44244941e-181,  2.16916649e-314,  2.16729105e-314,
         3.75314712e-265,  2.16916471e-314,  2.19200087e-314,
         2.40569274e+237,  2.16783151e-314,  2.19200447e-314,
         3.19858447e-279,  2.16793256e-314,  2.19330766e-314,
         4.31912939e+296,  2.19200968e-314,  2.16724114e-314,
         1.41840350e-275,  2.19200629e-314,  2.16724114e-314,
        -3.63623861e+152,  2.19200971e-314,  2.16724114e-314],
       [-3.73326441e-241,  2.19200632e-314,  2.16724161e-314,
        -2.95155520e+018,  2.19200636e-314,  2.16724161e-314,
      

For some numbers, a function already exists, such as ones (`np.ones`) and zeros (`np.zeros`):

In [25]:
np.zeros((5,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

If you're unsure about the arguments, you can always use the `help` function, or go online and use the documentation of `numpy` @ https://docs.scipy.org/doc/numpy/reference/index.html

In [26]:
help(np.arange) # Python method
?np.arange # Jupyter method

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

## Indexing
Now that we know how to create an array and determine its basic attributes, we can try to access some of the data in an array. Let's first try to access one cell in an vector. This works just like indexing a list.

In [27]:
vector = [1,2,3]
print(vector[0])
print(np.array(vector)[0])

1
1


You can also use the other notations from lists, such as `-1` for the last element and `:` for all elements.

In [28]:
print(vector[-1])
print(np.array(vector)[-1])

print(vector[:])
print(np.array(vector)[:])


3
3
[1, 2, 3]
[1 2 3]


The same works for multiple dimensions, such as matrices, but now you need to give the location in two dimensions. It is better to use `[row, column]` than `[row][column]` as the latter creates a temporary object, which is wasteful and thus slower.

In [29]:
vector = [[1,2,3],[4,5,6]]
print(vector[0][0])
print(np.array(vector)[0][0])

print(np.array(vector)[0, 0])  # better

print(np.array(vector)[0, :])  # first row, all columns
print(np.array(vector)[:, -1])  # all rows, last column


1
1
1
[1 2 3]
[3 6]


#### Indexing with arrays
Getting single elements from an array is useful, but getting multiple elements at the same time is even more useful, as we'll see soon. You can achieve this by indexing arrays with arrays.

In [30]:
vector = np.arange(0,100)
index = np.array([0,1,50,99])  # first, second, 51th and last elements
vector[index]

array([ 0,  1, 50, 99])

The same works in multiple dimensions, although you now need two indexes, one for each dimensions. These indices need to be of the same length as they describe the same elements.

In [32]:
vector = np.arange(0,100).reshape((5,20))
index_rows = np.array([0,1,4])  # first, second, and last rows
index_columns = np.array([0,1,19])  # first, second, and last columns

vector[index_rows, index_columns]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

#### Logical indexing
Two dimensional indexing is only useful if you already know the exact position of the elements you're interested in. Often you're interested in these values because they have something in common. Let's say you want to get all values greater than 5 in the array. With logical (using logic) indexing, this can be quickly achieved.

Remember logical operators from the previous courses? These operations return `True` or `False`, also commonly represented by `1` and `0` (useful for calculations).

In [33]:
25 > 5

True

In [35]:
np.arange(0,50) < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [36]:
sum(np.arange(0,50) > 5)

44

This `Boolean` array can be used for indexing as well, which can create some really powerful indexing methods.

In [38]:
vector = np.arange(0,50)
vector[vector > 5]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
matrix = vector.reshape((10,5))
matrix[matrix>5]  # also works in multiple dimensions
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

You can also directly replace values with indexing.

In [46]:
matrix[matrix > 5] = 0
matrix

array([[0, 1, 2, 3, 4],
       [5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Copies and views
When editing parts of an array using above indexes, take care of copies vs views. Editing a view on an array, will edit the original array, but editing the copy will not.

In [48]:
a = np.arange(25)

# Editing the view (using a slice) modifies the original array
randomname = a[0:10]
randomname[:] = -1
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
# Editing the original array will show up in the view
a[0:5] = -5
randomname

array([-5, -5, -5, -5, -5, -1, -1, -1, -1, -1])

Only slices (`:`) and explicitely calling `.view()` on an array will create views. Using other indexing methods won't.

In [50]:
# Indexing with an array won't create a view, but a copy, which won't update the original array.
copy = a[[15,-2,-1]]
copy[:] = 9999
a

array([-5, -5, -5, -5, -5, -1, -1, -1, -1, -1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Note that the above only applies when creating variables of which reference a part of an array. Direct indexing will still work for editing. When you want to create a copy, you can also always 

## Broadcasting
You know what happens when you execute `2*2` and probably also for `[1,2] + 1`. But what happens when you do `[1,2]*[1,2]`? Or `[1,2]*[1,2,3]`?
These behaviours on arrays are known as broadcasting.

In [51]:
# Same sized arrays
a = np.array([1,2,3])
b = np.array([1,2,3])

print("Addition")
print(a + b)
print("Multiplication")
print(a * b)

Addition
[2 4 6]
Multiplication
[1 4 9]


As you can see, broadcasting works on an element by element basis. But what happens on different sizes?

In [52]:
a = np.array([1,2,3])
b = np.array([1,2,3]).reshape(3,1)  # column vector

a * b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

Numpy can broadcast your arrays when the dimensions (starting at the trailing dimensions, working forward) either match in size or one of them is one. The number of dimensions don't have to match, as the smaller array will be repeated to match.

Some examples of sizes when you broadcast C = A * B

| _ | d  | d  |
|---|---|---|
| A | 3 | 1 |
| B | 1 | 1 |
| C | 3 | 1 |


| _ | d | d | d |   |
|---|---|---|---|---|
| A | 1 | 3 | 1 |   |
| B | _ | 1 | 1 |   |
| C | 1 | 3 | 1 |   |


In [54]:
a = np.random.rand(5,1,1)
b = np.random.rand(2,2,1)  # can be expanded to (1,2,1)

print("Shape of a")
print(a.shape)
print("Shape of b")
print(b.shape)

c = a*b
print("Shape of c")
print(c.shape)

Shape of a
(5, 1, 1)
Shape of b
(2, 2, 1)


ValueError: operands could not be broadcast together with shapes (5,1,1) (2,2,1) 

For more documentation on broadcasting, see: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

## Common methods
Numpy has way more functionality than the above, which is why you should keep its documentation at hand. Many calculus operations are available and there are often multiple ways to do the same thing.

## Excercise
What is the sum of all numbers above 427 in a 200x200 matrix of all numbers from 1 up and to 40000? And what about below 42? And what if you combine them?

## Further reading
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
